/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Card: typeof import('./components/Card.vue')['default']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    Loading: typeof import('./components/Loading.vue')['default']
  }
}
